# Default values for ci3.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
hostName: cleo-ci.health-samurai.io
ingress:
  enabled: true
  hosts:
  - cleo-ci.health-samurai.io

image:
  repository: eu.gcr.io/vivid-kite-171620/ci3
  tag: 0.0.5
  pullPolicy: Always

cacheBucket: cleo-ci-cache

service:
  args: ["server"]
  name: nginx
  type: NodePort
  externalPort: 80
  internalPort: 8888
