# Default values for ci3.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
hostName: ci.health-samurai.io
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "gce"
  tls:
  - hosts:
    - ci.health-samurai.io
    secretName: tls
  hosts:
  - ci.health-samurai.io

image:
  repository: aidbox/ci3
  tag: 0.0.1
  pullPolicy: IfNotPresent

service:
  args: ["server"]
  name: nginx
  type: NodePort
  externalPort: 80
  internalPort: 8888
