apiVersion: ci3.io/v1
branch: production
commit:
  author:
    email: muradbei@gmail.com
    name: Aitem
    username: Aitem
  id: 275f3e04e1322c2b5a4eef39c3c25dd419740853
  message: fix increment triumvirate Id
  timestamp: 2017-11-02T13:53:10+03:00
  url: https://github.com/HealthSamurai/tealnet/commit/275f3e04e1322c2b5a4eef39c3c25dd419740853
diff: null
hashcommit: 275f3e04e1322c2b5a4eef39c3c25dd419740853
kind: Build
metadata:
  clusterName: ""
  creationTimestamp: 2017-11-02T15:14:01Z
  deletionGracePeriodSeconds: null
  deletionTimestamp: null
  name: tealnet-1509635641452222222222fdfdfdf
  namespace: default
  resourceVersion: "20956665"
  selfLink: /apis/ci3.io/v1/namespaces/default/builds/tealnet-1509635641452
  uid: 7500d546-bfe0-11e7-932d-42010a840087
repository: tealnet
status: pending
