apiVersion: "ci3.io/v1"
kind: Build
metadata:
  name: build-2
  label:
    system: ci
status: peinding
environment:
  GIT_COMMIT:
    command:
      git rev-parse --short HEAD
pipeline:
- type: env
  DOCKER_REPO: eu.gcr.io/vivid-kite-171620/ci3:latest
  GIT_COMMIT: 
    command: "git rev-parse --short HEAD"
- type: bash
  command: while :; do echo 'Wait'; sleep 1; don:e
- type: maven
  command: restore-cache
  key: ci3
- type: lein
  command: test
- type: lein
  command: uberjar
- type: maven
  command: save-cache
  key: ci3
- type: bash
  command: docker login -u _json_key -p "$DOCKER_KEY" https://eu.gcr.io
- type: bash
  command: docker build -t $DOCKER_REPO:v_$GIT_COMMIT .
- type: bash
  command: docker tag $DOCKER_REPO:v_$GIT_COMMIT $DOCKER_REPO:latest
- type: bash
  command: docker push $DOCKER_REPO:v_$GIT_COMMIT
- type: bash
  command: docker push $DOCKER_REPO:latest
- type: bash
  command: helm upgrade --set image.tag=v_$GIT_COMMIT,image.repository=$DOCKER_REPO -i web-hook ci3
