apiVersion: "zeroci.io/v1"
kind: Build
metadata:
  name: build-2
  label:
    system: ci
status: peinding
pipeline:
 - type: maven
   command: restore-cache
 - type: lein
   command: test
 - type: lein
   command: uberjar
 - image: busybox
   command: ls -lah /
 - type: docker
   command: build
   image: eu.gcr.io/aidbox-next/ci3
 - type: lein
   command: deps
 - type: maven
   command: save-cache
