apiVersion: "zeroci.io/v1"
kind: Build
metadata:
  name: build-2
  label:
    system: ci
status: peinding
environment:
  GIT_COMMIT: "$(git rev-parse --short HEAD)"
pipeline:
- type: maven
  command: restore-cache
  key: ci3
- type: lein
  command: test
- type: lein
  command: uberjar
- type: maven
  command: save-cache
  key: ci3
- type: bash
  command: docker login -u _json_key -p "$DOCKER_KEY" https://eu.gcr.io
- type: env
  GIT_COMMIT:
    command: "git rev-parse --short HEAD"
- type: bash
  command: docker build -t eu.gcr.io/aidbox-next/ci3:$GIT_COMMIT .
- type: bash
  command: docker tag eu.gcr.io/aidbox-next/ci3:$GIT_COMMIT eu.gcr.io/aidbox-next/ci3:latest
- type: bash
  command: docker push eu.gcr.io/aidbox-next/ci3:$GIT_COMMIT
- type: bash
  command: docker push eu.gcr.io/aidbox-next/ci3:latest
- type: bash
  command: helm upgrade --set image.tag=$GIT_COMMIT,image.repository=eu.gcr.io/aidbox-next/ci3 -i web-hook ci3
