apiVersion: "ci3.io/v1"
kind: Repository
metadata:
  name: ci3
url: https://bitbucket.org/healthsamurai/ci3
type: bitbucket
fullName: HealthSamurai/ci3
oauthConsumer:
  token:
    valueFrom:
      secretKeyRef:
        name: bitbucket
        key: token 
