apiVersion: "ci3.io/v1"
kind: Repository
metadata:
  name: ci3
url: https://github.com/HealthSamurai/ci3.git
type: github
fullName: HealthSamurai/ci3
oauthConsumer:
  token:
    valueFrom:
      secretKeyRef:
        name: github
        key: token 
