apiVersion: v1
data:

  #
  # 1. Go to GCE Console > IAM & Admin > Roles
  # 2. Create new role ContainerMaster with Cloud Container * permissions
  # 3. Go to GCE Console > IAM & Admin > Service accounts
  # 4. Create new service account ci3-docker with role Custom > ContainerMaster
  # 5. Select Furnish a new private key and create account
  # 6. Encode obtained key and put it to key field
  #
  # echo -n "YOUR-VALUE" | base64 -w 0

  key: - PUT-YOUR-VALUE-HERE -
kind: Secret
metadata:
  name: docker-registry
  namespace: default
type: Opaque
