apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: builds.ci3.io
spec:
  scope: Namespaced
  group: ci3.io
  version: v1
  names:
    kind: Build
    plural: builds
    singular: build
